### ISSUE TITLE
Multiple  DbContextExtensions.cs created when running the tool on Multiple databases

### ISSUE THREAD

**Issue by KayakFisher205** [ErikEJ/erikej.github.io#20]
When using 2.4.217.0, EF Core 5.0 Preview, Advanced, Generate stored procedure Mappings (preview) on a database, it works great. When I pointed to another database, there was a DbContextExtensions.cs file in the new folder that was conflicting with the first one, for a different database, in a different folder. 

If I move the static class of each of the DbContextExtensions.cs files to a namespace, based on the folder path, it works fine.

**Comment by ErikEJ** [comment]
Thanks for trying out this preview feature, I will investigate a solution for this.
