### ISSUE TITLE
Unable to find "generate stored procedure mapping" as mentioned in the blog

### ISSUE THREAD

**Issue by balajeek** [ErikEJ/erikej.github.io#30]
Hi there
Great tool, it saved my life and I so far used the reverse engineer to add many of my tables, today I tried adding a stored procedure and I see it created two new files, one as dbcontext and dbcontext extension.

I am not sure how would I use or call the stored procedure in my controller class as its not found.
then I found the blog where you mentioned the latest version allows to include stored procedures with "generate stored procedure mappings" from the option dialog.

when I go the reverse engineer menu and select the database connection and the dialog appears but I don't see any option as such to enable as you mentioned.

am I missing something, I appreciate your help. thanks.

**Comment by ErikEJ** [comment]
Now you just pick them from the UI, see the wiki post here: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#sql-server-stored-procedures - let me know if that is unclear!
