### ISSUE TITLE
Translation of table and colum names integrated with entity framework

### ISSUE THREAD

**Issue by alexsosa2000** [ErikEJ/erikej.github.io#32]
Just starting our first .NET project which will eventually have user interface in three languages.

Newbie question. Is there is a way to integrate localization of table and column names with Entity Framework. Seems like a natural extension to EFCore Power Tools.

Thank you very much.

Alex

**Comment by ErikEJ** [comment]
Not out of the box - also seems odd to directly expose your database columns to the end user?

You could consider using MS_Description - they are scaffolded as Comments, and can be read programmatically.

**Comment by alexsosa2000** [comment]
Thank you for the excellent lead :)
