### ISSUE TITLE
string_split is not working in database first approach.

### ISSUE THREAD

**Issue by vineshkamat** [ErikEJ/erikej.github.io#48]
@ErikEJ  Please find the git repo below. https://github.com/vineshkamat/SampleStringSplitApplication

Am using the Database first approach in entity framework. I have imported the table from the database  and trying to run the string_split function. Getting the  below error.

System.NotSupportedException: 'The specified method 'System.Linq.IQueryable`1[DbEnity.StringSplitResult] String_split(System.String, System.String)' on the type 'SampleProjectEnity.DbEntities' cannot be translated into a LINQ to Entities store expression.'

**Comment by ErikEJ** [comment]
Database first is unimportant

**Comment by ErikEJ** [comment]
It may not work with EDMX, never tested it, but the VS Data Model wizard can easily generate a "Code First Model" from an existing database.

**Comment by vineshkamat** [comment]
Used VS Model wizard and generated the "Code First Model" in the repo and facing the same issue.

**Comment by ErikEJ** [comment]
Have you updated the git repo?

**Comment by ErikEJ** [comment]
You had this line wrong:

            modelBuilder.Conventions.Add(new FunctionsConvention<DbContext>("dbo"));

changing it makes it work now:

            modelBuilder.Conventions.Add(new FunctionsConvention<TestModel>("dbo"));
