### ISSUE TITLE
Power Tools Hangs Visual Studio 2022 64-Bit  v17.5.0

### ISSUE THREAD

**Issue by stevenmcneese** [ErikEJ/erikej.github.io#50]
I started a new Class Library project after installing Power Tools from marketplace.  I selected net 7.0.  I right clicked on the solution and selected EF Core Power Tools/Reverse Engineer.  I selected an existing connection I had in the solution and set the options:

Pluralize or singularize generated object names
Use DataAnnotation attributes to configure the model
Install the EF Core provider package in the project

And under advanced:

Use many to many entity
Split DbContext into Configuration classes

After clicking ok, I let it run but after 5 minutes nothing happened.  When I tried to navigate in Visual Studio, nothing happened.  I opened file explorer to see if any files had been built and didn't see anything.  Next I killed VS using task manager.  When i opened the solution, they files had been built and everything seemed to look correct.
![image_480](https://user-images.githubusercontent.com/19170745/220747369-0b92a79f-c8b6-4b52-844e-16afc7e6d24e.png)
![image_360](https://user-images.githubusercontent.com/19170745/220747400-2ca5ed67-c4d4-42ef-9c2a-89d16ec18a2f.png)

**Comment by ErikEJ** [comment]
I am guessing your database server is far away and/or very slow. 

Please share details (as requested when you created this issue)

**Comment by ErikEJ** [comment]
Sorry - I meant create an issue here; https://github.com/ErikEJ/EFCorePowerTools and provide detailed repro steps
