### ISSUE TITLE
Renaming of procs and views?

### ISSUE THREAD

**Issue by carib247** [ErikEJ/erikej.github.io#51]
Wondering if renaming of procs and views is anywhere in the future? I normally have several procs that are named the same in every schema - such as Ins_exceptionlog. Views are often named differently, although with microservices I can see the same proc appearing in multiple schemas, such as vw_shoplist or vw_productlist. For now, I will run a script to modify and overwrite procs and view names. Just wondering what additional features might be planned. Great tool.

**Comment by ErikEJ** [comment]
@carib247 You can already do that: https://github.com/ErikEJ/EFCorePowerTools/wiki/Reverse-Engineering#custom-renaming-with-efptrenamingjson

**Comment by ErikEJ** [comment]
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
